### ISSUE TITLE
Explicitly present current design problems

### ISSUE THREAD

**Issue by tlaurion** [zakqwy/NSA-B-GONE#2]
`I will tell you what needs to be done (if you're so inclined), or how you can make the existing design work.`

@zakqwy : Please do :)

**Comment by zakqwy** [comment]
Hey! Thanks for the comment. Right now there are three problems I've identified. I think I know how to fix them, I just don't have the time right now:

1. The fab service I used for the prototype doesn't produce flat flex boards at the same thickness as the measured cable end. I think the cable end either has a stiffener or it's made of thicker polyamide. I had to shim the prototype using a few thicknesses of tape which resulted in a somewhat unreliable connection. Solution here is to try a thicker (or stiffened) flat flex part from another fab.
2. Rather than measure the existing cable, I designed the plug end cutout based on the Molex FPC connector's spec sheet. The prototype's cable end is a bit short compared to the original cable, which may also contribute to the somewhat unreliable connection. Solution here is to measure the existing IO cable, compare it to the design, and modify the design as needed to better copy the existing IO cable.
3. The Molex connector is mounted too far up on the screen. I miscalculated the offset from my initial measurements so the connector hits the back of the battery tray, necessitating some connector surgery. Solution here is to move the Molex connector down in the PCB design, but this will take a bit of routing as a few of the lines jump around to the USB switches. 

While I'm doing some rerouting, I'll also probably lengthen the board a bit so the connector doesn't need to be butchered more to fit around the ATtiny88. And if I'm doing all that, I might as well switch to a more ubiquitous ATtinyx5, or maybe one of those super tiny 8-DFN ATtiny4/5/9/10s (2x2mm!). I may get to this over summer '19 but no guarantees.

**Comment by tlaurion** [comment]
@BlackMaria?

**Comment by BlackMaria** [comment]
Yeah, my theory was to either make the boards on mica which zak's fab doesnt offer (but, I have access to a role of mica/copper pcb paper).

Otherwise, just an idea if mica is too expensive/difficult to print a full PCB, and if you can find a some mica pcb paper scraps ( adafruit sells 6x6 for 10$ ):
1. Flip the pins on the molex connector, and place it on the other side of the PCB, and send that to the fab.
1. DIY make a mica pcb with two joined molex footprints ( or just a bunch of molex spaced lines across the whole sheet and cut as needed )
1. reflow the mica pcb to the fiberglass one. 

The end result of this would have a protruding mica connector with enough space to fit the connector
Does that sound interesting?

I forgot to say.  thanks for this project its a great idea.

**Comment by tlaurion** [comment]
@zakqwy?

**Comment by zakqwy** [comment]
I think that is an interesting path to explore, I just don't have the time to spin a new board. I'll happily accept a PR if you test this and it works!

**Comment by tlaurion** [comment]
@BlackMaria : any progress on a design? Could even, possibly maybe, be made under grant.
